CREATE TABLE IF NOT EXISTS HEADERS (
       ID   SERIAL PRIMARY KEY,
       DOCUMENT_TYPE VARCHAR(30),
       RECEIVER_SYSTEM_TYPE VARCHAR (15),
       DOCUMENT_NUMBER INTEGER,
       DOCUMENT_DATE_1 DATE,
       DOCUMENT_DATE_2 DATE,

       SENDER_ILN BIGINT,
       SENDER_CODE_BY_RECEIVER BIGINT,
       SENDER_NAME VARCHAR (30),
       SENDER_ADDRESS VARCHAR(200),

       RECEIVER_ILN BIGINT,
       RECEIVER_CODE_BY_RECEIVER BIGINT,
       RECEIVER_NAME VARCHAR (30),
       RECEIVER_ADDRESS VARCHAR (200)

);
CREATE TABLE IF NOT EXISTS DETAILS (
       ID   SERIAL PRIMARY KEY,
       LINE_NUMBER SMALLINT,
       SUPPLIER_ITEM_CODE SMALLINT,
       ITEM_DESCRIPTION VARCHAR(255),
       INVOICE_QUANTITY INTEGER,
       INVOICE_UNIT_NET_PRICE NUMERIC DEFAULT 0
);

